name: Python package

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
          python-version: 3.13
      - run: uv sync
      - uses: astral-sh/ruff-action@v3
